#!/bin/bash

useradd -m -s /bin/bash py37
echo "py37:passwd" | chpasswd
adduser py37 sudo

git clone https://github.com/FarAway6834/py37env_home /home/py37/py37env_home
/home/py37/py37env_home/initial_setting
rm ./initial_setter
